In [1]:
# ReLu
import numpy as np

In [2]:
inputs = [0,2,-1,3.3,-2.7,1.1,2.2,-100]
output = np.maximum(0,inputs)
print(output)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [3]:
#ReLu activation
class Activation_Relu:
    def forward(self,inputs):
        self.output = np.maximum(0,inputs)

In [4]:
inputs = [
    [0.3,0.22,0.4],
    [0.4,0.91,0.2],
    [0.11,0.1,0.4]
]
exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
print(probabilities)
np.sum(probabilities, axis=1)


[[0.33021966 0.30483117 0.36494917]
 [0.2870246  0.47797954 0.23499587]
 [0.30061831 0.29762711 0.40175458]]


array([1., 1., 1.])

In [ ]:
# softmax activation
class Activation_Softmax:
    def forward(self,inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities