In [1]:
import numpy as np

In [ ]:
# dot product
inputs = [0.3, 0.5, 0.1]
weights= [
     [0.3,0.1,0.4],
     [0.0,0.9,0.3],
     [0.1,0.2,0.3]]
biases = [0.5,0.9,0.1]
outputs = np.dot(inputs,weights) + biases
outputs

array([0.6, 1.4, 0.4])

In [4]:
# batch of inputs
inputs = [
    [0.3,0.22,0.4],
    [0.4,0.91,0.2],
    [0.11,0.1,0.4]
]
weights= [
     [0.3,0.1,0.4],
     [0.0,0.9,0.3],
     [0.1,0.2,0.3]
]
biases = [0.5,0.9,0.1]

outputs = np.dot(inputs,np.array(weights).T) + biases
outputs

array([[0.772, 1.218, 0.294],
       [0.791, 1.779, 0.382],
       [0.703, 1.11 , 0.251]])

In [6]:
# 2 layer neuron
inputs_1 = [
    [0.3,0.22,0.4],
    [0.4,0.91,0.2],
    [0.11,0.1,0.4]
]
weights_1 = [
     [0.3,0.1,0.4],
     [0.0,0.9,0.3],
     [0.1,0.2,0.3]
]
biases_1 = [0.5,0.9,0.1]

weights_2 = [
     [0.3,0.1,-0.4],
     [0.0,0.4,0.3],
     [0.1,0.7,0.7]
]
biases_2 = [0.1,0.49,0.31]

# converting lists to numpy arrays
inputs_1 = np.array(inputs_1)
weights_1 = np.array(weights_1)
weights_2 = np.array(weights_2)
biases_1 = np.array(biases_1)
biases_2 = np.array(biases_2)

layer_1_outputs = np.dot(inputs_1,weights_1.T) + biases_1
layer_2_outputs = np.dot(layer_1_outputs,weights_2.T)  + biases_2

print(layer_1_outputs)
print(layer_2_outputs)


[[0.772 1.218 0.294]
 [0.791 1.779 0.382]
 [0.703 1.11  0.251]]
[[0.3358 1.0654 1.4456]
 [0.3624 1.3162 1.9018]
 [0.3215 1.0093 1.333 ]]
